apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: lan.quanby.nl
  namespace: cert-manager
spec:
  secretName: lan.quanby.nl-tls
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
  dnsNames:
  - '*.lan.quanby.nl'
  - lan.quanby.nl
