apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: lab.quanby.nl
spec:
  secretName: lab.quanby.nl-tls
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
  dnsNames:
  - '*.lab.quanby.nl'
  - lab.quanby.nl
