apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: tls-rancher-demo
  namespace: default
spec:
  dnsNames:
  - rancher-demo.lab.quanby.nl
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-staging
  secretName: tls-rancher-demo
