apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: tls-rancher-ingress
  namespace: cattle-system
spec:
  dnsNames:
  - rancher.lab.quanby.nl
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-staging
  secretName: tls-rancher-ingress
